### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/atsign.dev#120]
Hi @cpswan I think this page is pulling automatically from the Pub.Dev pages.  I found some inconsistencies in the usage of @sign (atsign) and @protocol (atprotocol).  

For example look at at_contacts_flutter and at_chat_flutter vs at_backupkey_flutter.

I didn't want to update anything in case its auto updating.  Also want to confirm is this intentional or should it be updated?

I opened another ticket on description inconsistencies as well issue #118 and #136

**Comment by cpswan** [comment]
It's not intentional. The descriptions need to be fixed in the various pubspec.yaml files, and then updates pushed to pub.dev, and then the libraries.md regenerated from what's on pub.dev.

Just like I did with the various at_tools READMEs, we probably need a bunch of issues raised to get the pubspec.yaml files straightened out.

**Comment by ksanty** [comment]
> It's not intentional. The descriptions need to be fixed in the various pubspec.yaml files, and then updates pushed to pub.dev, and then the libraries.md regenerated from what's on pub.dev.
> 
> Just like I did with the various at_tools READMEs, we probably need a bunch of issues raised to get the pubspec.yaml files straightened out.

Thanks @cpswan.  Kevin is going to read through them and identify the gaps.  I'm going to close this issue.  Please refer to issue #118.
