### ISSUE TITLE
Hugo / docsy theme issue

### ISSUE THREAD

**Issue by nickelskevin** [atsign-foundation/atsign.dev#19]
**Describe the bug**
The HugoBuild GitHub action fails when it runs content that uses the Docsy theme.
Some useful info can be found [here](https://github.com/kubernetes/contributor-site/issues/123)

**To Reproduce**
1. First I checked in some content to a new "poc" branch
2. Then I saw that the HugoBuild started, but failed
3. And then after investigating, discovered that there is an issue with the version of Hugo

**Expected behavior**
Checking into a "poc" branch would not be deployed to staging.
Hugo should be configured to work with the Docsy theme.

**Screenshots**
<img width="978" alt="Screen Shot 2021-05-17 at 5 07 32 PM" src="https://user-images.githubusercontent.com/1827777/118571260-80146480-b732-11eb-883a-ae271e45066a.png">

**Smartphone (please complete the following information):**
Not a device related issue.

**Were you using an @application when the bug was found?**
Not an app related issue.

**Additional context**

**Comment by cpswan** [comment]
Wow, that's quite a theme.

Fixed by:

32669078a1c4b8eaa71cf8dab98fbb5cd9dc8fd1 - Docsy needs Hugo 0.75, we were on 0.74.3, now using 0.83.1
b8174e63fd04444febfd9f817c4496e07623b85a - Docsy needs recursive submodules
8d72d42a51e97f71327957091d7cb8aab40ebe76 - Action needs to setup node.js for postcss-cli
9490403be0521ee8309021231bd0dee5c778c925 - .gitignore for npm stuff to avoid clutter
814d0159c605985e1b3dbdb41f7e3dd5dd760a96 - npm definitions from google/docsy-example
