### ISSUE TITLE
HackOWASP 4.0 (March 11 - 13)

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#402]
Leads : @Shubhangi0304  & @Jatinpandya26 

1. Event Type: Hackathon
2. Website: https://hackowasp.live
3. Expected participants: 1500
4. atsigns expected : 2000

Activities:

- [x] Tshirt Giveaway 
- [x] Treasure Hunt Campaign 
- [x]  Session on the @ platform
- [x] Opening Note 
- [x] AMA about @ Platform

**Comment by Jatinpandya26** [comment]
- [ ] Giveaway (This Weekend) - Online
- [ ] Treasure hunt campaign - Potential @mosphere pro campaign 
- [ ] Giveaway (This Weekend) - Offline
- [ ] Opening Note for us
- [ ] AMA about @ Platform

***Note** - Might be postponed a week late due to management issues for dates in the week hack has been planned now.

**Comment by knowShubhangi** [comment]
Dates of the hackathon were changed.
Tshirt giveaway - ongoing
