### ISSUE TITLE
Dude App Readiness

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#404]
Lead : @anthonyvprakash 

- [x] Work with Curtly and the Engg team to get the app to a point where it can be Open Sourced
- [x] Work with @cpswan on new Repo and other Github formalities.

**Comment by hakeemawbrey** [comment]
Worked with curtly to create branding, colors, fun designs for dude app. Going to work with him to create more designs and figure out implementation.

**Comment by anthonyvprakash** [comment]
@TylerTrott  - is anything pending on the app to make it available for open sourcing?

**Comment by TylerTrott** [comment]
@anthonyvprakash I think we're good to go. I just merged Chris' PR. One thing I would like to integrate is a ResetKeychain() function so that an AtSign is not stuck on the onboarding screen.

@yahu1031 || @CurtlyCritchlow do you have availability for this integration?

**Comment by yahu1031** [comment]
@TylerTrott what do you mean by... 

> AtSign is not stuck on the onboarding screen.

?

**Comment by TylerTrott** [comment]
> @TylerTrott what do you mean by...
> 
> > AtSign is not stuck on the onboarding screen.
> 
> ?

So when I onboard as an atsign, my keychain is corrupted as I logged in a while back but because we do not have an option to reset the keychain, I am no longer able to authenticate with my keys. Because I have logged in before, it automatically on-boards my previously authenticated atsign but the atsign is null. The only solution (on iOS) is to integrate the resetKeychain() func. Make sense?

**Comment by CurtlyCritchlow** [comment]
Reset at-sign button added to the first screen, make a pull request from the @dude repo.

We're not ready for open sourcing as yet because the sync not working and the notification feature not implemented as yet. @kalluriramkumar said once monitor connection working the sync should be automatic. I'm trying to meet with him to debug the sync issue.

**Comment by yahu1031** [comment]
@TylerTrott @CurtlyCritchlow I know a fix for this keychain thing. But must be handled from the app level. 

![image](https://user-images.githubusercontent.com/35523357/161931342-7f989ce0-bd05-422d-a494-dc648531abb3.png)
